// <auto-generated />
namespace MvcEight.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mg32 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg32));
        
        string IMigrationMetadata.Id
        {
            get { return "201611161515587_mg32"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
